spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
jwt:
  secret: ${JWT_SECRET}
application:
  key:
    id: ${B2_KEY_ID}
    value: ${B2_VALUE}
bucket:
  id: ${B2_BUCKET_ID}