create table if not exists account
(
    account_id        bigint generated by default as identity primary key,
    username          varchar(30) not null unique,
    role              varchar,
    password          varchar,
    email             varchar(64),
    is_verified_email boolean,
    profile_picture   varchar,
    last_name         varchar,
    first_name        varchar
);